// <auto-generated />
using System;
using Jenga.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jenga.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623122504_AddGonderiPaketiTableToDB")]
    partial class AddGonderiPaketiTableToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jenga.Models.IKYS.BirimTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Aktif")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int?>("AmirId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KisaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Sira")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BirimTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.IKYS.GorevTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<long?>("BirimId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KisaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<bool?>("Vekil")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GorevTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.IKYS.IsBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AyrilmaSebebi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AyrilmaTar")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BaslamaTar")
                        .HasColumnType("datetime2");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("CalismaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmeklilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IzinDonemiBasTar")
                        .HasColumnType("datetime2");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SGKBasTar")
                        .HasColumnType("datetime2");

                    b.Property<string>("SGKSicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnvanId")
                        .HasColumnType("int");

                    b.Property<int>("VakifOncesiPrimGunSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("GorevId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UnvanId");

                    b.ToTable("IsBilgileri_Table");
                });

            modelBuilder.Entity("Jenga.Models.IKYS.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asker_sivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SicilNo")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tahsili")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personel_Table");
                });

            modelBuilder.Entity("Jenga.Models.IKYS.UnvanTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<short?>("GorTipId")
                        .IsRequired()
                        .HasColumnType("smallint");

                    b.Property<string>("KisaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UnvanTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.AniObjesiTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("StokluMu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("AniObjesiTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.DagitimYeriTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DagitimYeriTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.DepoHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("AniObjesiId")
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GirisCikis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HedefDepoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemYapan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KaynakDepoId")
                        .HasColumnType("int");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AniObjesiId");

                    b.HasIndex("HedefDepoId");

                    b.HasIndex("KaynakDepoId");

                    b.HasIndex("KaynakId");

                    b.ToTable("DepoHareket_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.DepoStok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AniObjesiId")
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SonAdet")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonIslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SonIslemYapan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AniObjesiId");

                    b.HasIndex("DepoId");

                    b.ToTable("DepoStok_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.DepoTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DepoTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.GonderiPaketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DagitimYeriTanimId")
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etiket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GonderiTakipNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GondermeAraci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GondermeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DagitimYeriTanimId");

                    b.HasIndex("IlId");

                    b.HasIndex("IlceId");

                    b.ToTable("GonderiPaketi_Table");
                });

            modelBuilder.Entity("Jenga.Models.MTS.KaynakTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KaynakTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngIlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlakaKodu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Il_Table");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IlId");

                    b.ToTable("Ilce_Table");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.MenuTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UstMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Webpart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.ModulTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgramAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebpartAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModulTanim_Table");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.PersonelMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuTanimId")
                        .HasColumnType("int");

                    b.Property<string>("Olusturan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuTanimId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelMenu_Table");
                });

            modelBuilder.Entity("Jenga.Models.IKYS.IsBilgileri", b =>
                {
                    b.HasOne("Jenga.Models.IKYS.BirimTanim", "BirimTanim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.IKYS.GorevTanim", "GorevTanim")
                        .WithMany()
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.IKYS.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.IKYS.UnvanTanim", "UnvanTanim")
                        .WithMany()
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirimTanim");

                    b.Navigation("GorevTanim");

                    b.Navigation("Personel");

                    b.Navigation("UnvanTanim");
                });

            modelBuilder.Entity("Jenga.Models.MTS.AniObjesiTanim", b =>
                {
                    b.HasOne("Jenga.Models.MTS.KaynakTanim", "KaynakTanim")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KaynakTanim");
                });

            modelBuilder.Entity("Jenga.Models.MTS.DepoHareket", b =>
                {
                    b.HasOne("Jenga.Models.MTS.AniObjesiTanim", "AniObjesiTanim")
                        .WithMany()
                        .HasForeignKey("AniObjesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.MTS.DepoTanim", "DepoTanim")
                        .WithMany()
                        .HasForeignKey("HedefDepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.MTS.DepoTanim", "KaynakDepoTanim")
                        .WithMany()
                        .HasForeignKey("KaynakDepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.MTS.DepoTanim", "KaynakTanim")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AniObjesiTanim");

                    b.Navigation("DepoTanim");

                    b.Navigation("KaynakDepoTanim");

                    b.Navigation("KaynakTanim");
                });

            modelBuilder.Entity("Jenga.Models.MTS.DepoStok", b =>
                {
                    b.HasOne("Jenga.Models.MTS.AniObjesiTanim", "AniObjesiTanim")
                        .WithMany()
                        .HasForeignKey("AniObjesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.MTS.DepoTanim", "DepoTanim")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AniObjesiTanim");

                    b.Navigation("DepoTanim");
                });

            modelBuilder.Entity("Jenga.Models.MTS.GonderiPaketi", b =>
                {
                    b.HasOne("Jenga.Models.MTS.DepoTanim", "DagitimYeriTanim")
                        .WithMany()
                        .HasForeignKey("DagitimYeriTanimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.Ortak.Il", "IlAdi")
                        .WithMany()
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.Ortak.Ilce", "IlceAdi")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DagitimYeriTanim");

                    b.Navigation("IlAdi");

                    b.Navigation("IlceAdi");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.Ilce", b =>
                {
                    b.HasOne("Jenga.Models.Ortak.Il", "IlTanim")
                        .WithMany()
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IlTanim");
                });

            modelBuilder.Entity("Jenga.Models.Ortak.PersonelMenu", b =>
                {
                    b.HasOne("Jenga.Models.Ortak.MenuTanim", "MenuTanim")
                        .WithMany()
                        .HasForeignKey("MenuTanimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jenga.Models.IKYS.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuTanim");

                    b.Navigation("Personel");
                });
#pragma warning restore 612, 618
        }
    }
}
