<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Ortak\**" />
	  <EmbeddedResource Remove="Ortak\**" />
	  <None Remove="Ortak\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Test\" />
		<Folder Include="ViewModels\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Jenga.Utility\Jenga.Utility.csproj" />
	</ItemGroup>

</Project>
